### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by wenjun-666** [Ernket/ARL-Finger-ADD-Go#4]
root@hcss-ecs-ba7e:~/ARL/ARL-Finger-ADD-Go-main# go run main.go -a
API url: https://*.*.*.*:5003/
[+] Login Success!!
Error parsing JSON: invalid character ']' looking for beginning of value
这个要怎么解决?

**Comment by Ernket** [comment]
应该是我在删除部分不算特征的指纹的时候气急败坏，多删了一个]，等我晚点找找看

**Comment by wenjun-666** [comment]
4721，4806，4926行‘’ ] ‘’前面多了 ‘’ ，‘’

**Comment by Ernket** [comment]
已经更新了一个新的文件，试试看新的，我本地测试没问题了
检查的时候还发现有两处地方的换行有点问题，不知道为什么，这些都去掉了

**Comment by Ernket** [comment]
检查的时候还发现有两处地方的换行有点问题，不知道为什么，这些都去掉了

**Comment by wenjun-666** [comment]
作者辛苦了，拜谢

**Comment by Ernket** [comment]
小事，感谢师傅及时反馈
